### ISSUE TITLE
update Allen Institute volume viewer url

### ISSUE THREAD

**Issue by toloudis** [ome/ome-ngff-validator#40]
The Allen Institute for Cell Science's volume viewer url is now `https://volumeviewer.allencell.org/viewer?url=url_to_single_omezarr0.4_image`
The current url used by the validator is to a build that may or may not be current/stable moving forward.
We are actively developing and will be renaming it soon (within a couple weeks).  There will be a shorter url name coming after the renaming but that url should stick long term.

**Comment by joshmoore** [comment]
:100: for stable, versioned URLs! :heart: Thanks, @toloudis
